### ISSUE TITLE
Code-style, License and more.

### ISSUE THREAD

**Issue by kacperduras** [orkin2913/Supervisor#2]
Nie widze najmniejszego sensu używania licencji GNU w tak małym projekcie. Lepszym rozwiązaniem byłoby użycie The MIT License, albo WTFPL. Proponuje także dostosować code-style do zasad umieszczonych tutaj: https://standardjs.com

**Comment by orkin2913** [comment]
Sposób licencjonowania zależy od autora, a nie od wielkości projektu :)
Jeżeli chodzi o code-style, to zapraszam do współpracy nad projektem.
